name: 'action_cable_example'

type: 'ruby:2.3'

web:
  upstream:
    socket_family: unix
    protocol: http
  commands:
    start: puma -e production -b unix://$SOCKET && sidekiq L /app/log/sidekiq.log
  locations:
    "/":
      root: "public"
      passthru: true
      expires: 1h
      allow: true

relationships:
  database: "database:postgresql"
  cache: "rediscache:redis"

disk: 2048

hooks:
  build: |
    gem install bundler
    RAILS_ENV=production bundle install --jobs 6 --without development test
    RAILS_ENV=production bundle exec rake assets:precompile
  deploy: |
    RACK_ENV=production bundle exec rake db:migrate

mounts:
  "/public/system": "shared:files/publicsystem"
  "/log": "shared:files/log"
  "/tmp": "shared:files/tmp"
