name: 'action_cable_example'

type: 'ruby:2.3'

web:
  upstream:
    socket_family: tcp
  commands:
    start: |
      rackup config.ru -s puma -E production -p $PORT
      sidekiq
  locations:
    "/":
      root: "public"
      passthru: true
      expires: 1h
      allow: true

relationships:
    database: "database:postgresql"

disk: 2048

hooks:
  build: |
    gem install bundler
    RAILS_ENV=production bundle install --jobs 6 --without development test
    RAILS_ENV=production bundle exec rake assets:precompile
  deploy: RACK_ENV=production bundle exec rake db:migrate

mounts:
 "/app/public/system": "shared:files/publicsystem"
 "/app/log": "shared:files/log"
 "/app/tmp": "shared:files/tmp"
